### PR TITLE
bump devDeps

### PR DESCRIPTION
**Pull request by legobeat**
- Bump and unpin devDependencies while keeping compatibility with runtime 
- npm dedupe; npm audit fix

#### Blocking
- #8
  - #6

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore debug@3.2.6
    @SocketSecurity ignore for-each@0.3.3
    @SocketSecurity ignore pathval@1.1.1
    @SocketSecurity ignore anymatch@3.1.3
    @SocketSecurity ignore loupe@2.3.7
    @SocketSecurity ignore check-error@1.0.3
    @SocketSecurity ignore fsevents@2.1.3
    @SocketSecurity ignore flat@4.1.1
    @SocketSecurity ignore define-properties@1.2.1


mocha legacy

**Comment by legobeat** [comment]
@SocketSecurity ignore ansi-regex@4.1.0
    @SocketSecurity ignore setimmediate@1.0.5
    @SocketSecurity ignore bs58@4.0.1
    @SocketSecurity ignore ripemd160@2.0.2
    @SocketSecurity ignore md5.js@1.3.5

legacy from devDep `ganache-cli`

**Review by leotm — COMMENTED** [review]
was about to run our `build` script locally to check `/dist`
but any idea why i'm unable to reach this branch?

```console
➜  GitHub nvm use 8
Now using node v8.17.0 (npm v6.13.4)
➜  GitHub gh repo clone MetaMask/ethjs-contract
Cloning into 'ethjs-contract'...
remote: Enumerating objects: 359, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 359 (delta 133), reused 168 (delta 123), pack-reused 162
Receiving objects: 100% (359/359), 910.04 KiB | 248.00 KiB/s, done.
Resolving deltas: 100% (197/197), done.
From github.com:ethjs/ethjs-contract
 * [new branch]      master     -> upstream/master
! Repository ethjs/ethjs-contract set as the default repository. To learn more about the default repository, run: gh repo set-default --help
➜  GitHub cd ethjs-contract
➜  ethjs-contract git:(main) git checkout devDeps-bumps
error: pathspec 'devDeps-bumps' did not match any file(s) known to git
➜  ethjs-contract git:(main) gh pr checkout 4
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (8/8), done.
remote: Total 12 (delta 8), reused 8 (delta 8), pack-reused 4
Unpacking objects: 100% (12/12), 57.96 KiB | 319.00 KiB/s, done.
From github.com:ethjs/ethjs-contract
 * [new ref]         refs/pull/4/head -> i3-BreakOutContractClass
Switched to branch 'i3-BreakOutContractClass'
```

`main` branch commits are correct, but

Screenshot 2023-11-16 at 2 02 25 pm

`gh pr checkout 4` seems to be taking me waay back to https://github.com/ethjs/ethjs-contract/pull/4

**Review by mcmire — APPROVED** [review]
Looks good.

**Comment by legobeat** [comment]
@leotm Looks like your `gh` is defaulting using the upstream repo as default remote. :shrug: 
You can confirm by `git remote -v`.
 
> ```
> From github.com:ethjs/ethjs-contract
>  * [new branch]      master     -> upstream/master
> ! Repository ethjs/ethjs-contract set as the default repository. To learn more about the  default repository, run: gh repo set-default --help
> ```

**Pull request merged**
