### PR TITLE
ci: move from TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by legobeat**
- Remove TravisCI and coveralls integrations
- Add GitHub Actions workflows
- devDeps: ganache-core@2.1.0 -> ganache-cli@^6.12.2
  - make tests pass  

Note: Currently, `npm install` will fail on native build step unless python2.7 is used. Since python2.7 is not available in GHA runtime by default anymore, this uses `pyenv` to get a local compatible python version for the `npm install` step.

In addition, the build will fail on Node.js versions >8. 

---
### Related
- `npm i` will fail if merged before #2 

#### Blocking
- #4 
- #5
- #6

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore ansi-regex@4.1.0

known CVE through `ganache-cli`

**Comment by legobeat** [comment]
@SocketSecurity ignore ganache-cli@6.12.2

shell access; native code; deprecated

**Comment by legobeat** [comment]
@SocketSecurity ignore ansi-regex@3.0.0
    @SocketSecurity ignore kind-of@6.0.2
    @SocketSecurity ignore handlebars@4.0.11
    @SocketSecurity ignore trim@0.0.1
    @SocketSecurity ignore crypto-js@3.1.8
    @SocketSecurity ignore stringstream@0.0.5
    @SocketSecurity ignore extend@3.0.1
    @SocketSecurity ignore estraverse@4.2.0
    @SocketSecurity ignore babel-plugin-transform-es3-property-literals@6.5.0
    @SocketSecurity ignore coinstring@2.3.0
    @SocketSecurity ignore uuid@2.0.3
    @SocketSecurity ignore ethereumjs-tx@1.3.4
    @SocketSecurity ignore hash-base@3.0.4
    @SocketSecurity ignore asn1@0.2.3
    @SocketSecurity ignore wordwrap@0.0.3
    @SocketSecurity ignore component-emitter@1.2.1
    @SocketSecurity ignore stream-browserify@2.0.1
    @SocketSecurity ignore url@0.11.0
    @SocketSecurity ignore esrecurse@4.2.1
    @SocketSecurity ignore browserify-rsa@4.0.1
    @SocketSecurity ignore buffer@4.9.1
    @SocketSecurity ignore querystring@0.2.0

unrelated

**Comment by legobeat** [comment]
It seems like `scrypt` has a native build-step which depends on python2.7, which is no longer available in GitHub Actions runner images. Adding a workaround using pyenv which can be removed when the dependency has been addressed.

**Review by mcmire — APPROVED** [review]
Looks good!

**Pull request merged**
